/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forget-password'
import { Route as LayoutadminAdminUsersRouteImport } from './routes/_layout/(admin)/admin.users'
import { Route as LayoutadminAdminTransactionsRouteImport } from './routes/_layout/(admin)/admin.transactions'
import { Route as LayoutadminAdminPrescriptionsRouteImport } from './routes/_layout/(admin)/admin.prescriptions'
import { Route as LayoutadminAdminPatientsRouteImport } from './routes/_layout/(admin)/admin.patients'
import { Route as LayoutadminAdminOrderRouteImport } from './routes/_layout/(admin)/admin.order'
import { Route as LayoutadminAdminMedicineRouteImport } from './routes/_layout/(admin)/admin.medicine'
import { Route as LayoutadminAdminInventoryRouteImport } from './routes/_layout/(admin)/admin.inventory'
import { Route as LayoutadminAdminDoctorsRouteImport } from './routes/_layout/(admin)/admin.doctors'
import { Route as LayoutadminAdminDashboardRouteImport } from './routes/_layout/(admin)/admin.dashboard'
import { Route as LayoutadminAdminConsultationsRouteImport } from './routes/_layout/(admin)/admin.consultations'
import { Route as LayoutadminAdminAppointmentsRouteImport } from './routes/_layout/(admin)/admin.appointments'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/auth/forget-password',
  path: '/auth/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutadminAdminUsersRoute = LayoutadminAdminUsersRouteImport.update({
  id: '/(admin)/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminTransactionsRoute =
  LayoutadminAdminTransactionsRouteImport.update({
    id: '/(admin)/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminPrescriptionsRoute =
  LayoutadminAdminPrescriptionsRouteImport.update({
    id: '/(admin)/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminPatientsRoute =
  LayoutadminAdminPatientsRouteImport.update({
    id: '/(admin)/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminOrderRoute = LayoutadminAdminOrderRouteImport.update({
  id: '/(admin)/admin/order',
  path: '/admin/order',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminMedicineRoute =
  LayoutadminAdminMedicineRouteImport.update({
    id: '/(admin)/admin/medicine',
    path: '/admin/medicine',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminInventoryRoute =
  LayoutadminAdminInventoryRouteImport.update({
    id: '/(admin)/admin/inventory',
    path: '/admin/inventory',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminDoctorsRoute = LayoutadminAdminDoctorsRouteImport.update({
  id: '/(admin)/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminDashboardRoute =
  LayoutadminAdminDashboardRouteImport.update({
    id: '/(admin)/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminConsultationsRoute =
  LayoutadminAdminConsultationsRouteImport.update({
    id: '/(admin)/admin/consultations',
    path: '/admin/consultations',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminAppointmentsRoute =
  LayoutadminAdminAppointmentsRouteImport.update({
    id: '/(admin)/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/admin/order': typeof LayoutadminAdminOrderRoute
  '/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/admin/users': typeof LayoutadminAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/admin/order': typeof LayoutadminAdminOrderRoute
  '/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/admin/users': typeof LayoutadminAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_layout/(admin)/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/_layout/(admin)/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/_layout/(admin)/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/_layout/(admin)/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/_layout/(admin)/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/_layout/(admin)/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/_layout/(admin)/admin/order': typeof LayoutadminAdminOrderRoute
  '/_layout/(admin)/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/_layout/(admin)/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/_layout/(admin)/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/_layout/(admin)/admin/users': typeof LayoutadminAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/appointments'
    | '/admin/consultations'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/inventory'
    | '/admin/medicine'
    | '/admin/order'
    | '/admin/patients'
    | '/admin/prescriptions'
    | '/admin/transactions'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/admin/appointments'
    | '/admin/consultations'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/inventory'
    | '/admin/medicine'
    | '/admin/order'
    | '/admin/patients'
    | '/admin/prescriptions'
    | '/admin/transactions'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/_layout/(admin)/admin/appointments'
    | '/_layout/(admin)/admin/consultations'
    | '/_layout/(admin)/admin/dashboard'
    | '/_layout/(admin)/admin/doctors'
    | '/_layout/(admin)/admin/inventory'
    | '/_layout/(admin)/admin/medicine'
    | '/_layout/(admin)/admin/order'
    | '/_layout/(admin)/admin/patients'
    | '/_layout/(admin)/admin/prescriptions'
    | '/_layout/(admin)/admin/transactions'
    | '/_layout/(admin)/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/(admin)/admin/users': {
      id: '/_layout/(admin)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutadminAdminUsersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/transactions': {
      id: '/_layout/(admin)/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof LayoutadminAdminTransactionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/prescriptions': {
      id: '/_layout/(admin)/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof LayoutadminAdminPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/patients': {
      id: '/_layout/(admin)/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof LayoutadminAdminPatientsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/order': {
      id: '/_layout/(admin)/admin/order'
      path: '/admin/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof LayoutadminAdminOrderRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/medicine': {
      id: '/_layout/(admin)/admin/medicine'
      path: '/admin/medicine'
      fullPath: '/admin/medicine'
      preLoaderRoute: typeof LayoutadminAdminMedicineRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/inventory': {
      id: '/_layout/(admin)/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof LayoutadminAdminInventoryRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/doctors': {
      id: '/_layout/(admin)/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof LayoutadminAdminDoctorsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/dashboard': {
      id: '/_layout/(admin)/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutadminAdminDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/consultations': {
      id: '/_layout/(admin)/admin/consultations'
      path: '/admin/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof LayoutadminAdminConsultationsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/appointments': {
      id: '/_layout/(admin)/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof LayoutadminAdminAppointmentsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutadminAdminAppointmentsRoute: typeof LayoutadminAdminAppointmentsRoute
  LayoutadminAdminConsultationsRoute: typeof LayoutadminAdminConsultationsRoute
  LayoutadminAdminDashboardRoute: typeof LayoutadminAdminDashboardRoute
  LayoutadminAdminDoctorsRoute: typeof LayoutadminAdminDoctorsRoute
  LayoutadminAdminInventoryRoute: typeof LayoutadminAdminInventoryRoute
  LayoutadminAdminMedicineRoute: typeof LayoutadminAdminMedicineRoute
  LayoutadminAdminOrderRoute: typeof LayoutadminAdminOrderRoute
  LayoutadminAdminPatientsRoute: typeof LayoutadminAdminPatientsRoute
  LayoutadminAdminPrescriptionsRoute: typeof LayoutadminAdminPrescriptionsRoute
  LayoutadminAdminTransactionsRoute: typeof LayoutadminAdminTransactionsRoute
  LayoutadminAdminUsersRoute: typeof LayoutadminAdminUsersRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutadminAdminAppointmentsRoute: LayoutadminAdminAppointmentsRoute,
  LayoutadminAdminConsultationsRoute: LayoutadminAdminConsultationsRoute,
  LayoutadminAdminDashboardRoute: LayoutadminAdminDashboardRoute,
  LayoutadminAdminDoctorsRoute: LayoutadminAdminDoctorsRoute,
  LayoutadminAdminInventoryRoute: LayoutadminAdminInventoryRoute,
  LayoutadminAdminMedicineRoute: LayoutadminAdminMedicineRoute,
  LayoutadminAdminOrderRoute: LayoutadminAdminOrderRoute,
  LayoutadminAdminPatientsRoute: LayoutadminAdminPatientsRoute,
  LayoutadminAdminPrescriptionsRoute: LayoutadminAdminPrescriptionsRoute,
  LayoutadminAdminTransactionsRoute: LayoutadminAdminTransactionsRoute,
  LayoutadminAdminUsersRoute: LayoutadminAdminUsersRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
