/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as callRouteRouteImport } from './routes/(call)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgetPasswordRouteImport } from './routes/auth/forget-password'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutpharmacistPharmacistSettingsRouteImport } from './routes/_layout/(pharmacist)/pharmacist.settings'
import { Route as LayoutpharmacistPharmacistPrescriptionsRouteImport } from './routes/_layout/(pharmacist)/pharmacist.prescriptions'
import { Route as LayoutpharmacistPharmacistOrdersRouteImport } from './routes/_layout/(pharmacist)/pharmacist.orders'
import { Route as LayoutpharmacistPharmacistMedicineRouteImport } from './routes/_layout/(pharmacist)/pharmacist.medicine'
import { Route as LayoutpharmacistPharmacistInventoryRouteImport } from './routes/_layout/(pharmacist)/pharmacist.inventory'
import { Route as LayoutpharmacistPharmacistDashboardRouteImport } from './routes/_layout/(pharmacist)/pharmacist.dashboard'
import { Route as LayoutpatientsPatientSettingsRouteImport } from './routes/_layout/(patients)/patient.settings'
import { Route as LayoutpatientsPatientPrescriptionsRouteImport } from './routes/_layout/(patients)/patient.prescriptions'
import { Route as LayoutpatientsPatientDashboardRouteImport } from './routes/_layout/(patients)/patient.dashboard'
import { Route as LayoutpatientsPatientConsultationsRouteImport } from './routes/_layout/(patients)/patient.consultations'
import { Route as LayoutpatientsPatientAppointmentsRouteImport } from './routes/_layout/(patients)/patient.appointments'
import { Route as LayoutdoctorsDoctorSettingsRouteImport } from './routes/_layout/(doctors)/doctor.settings'
import { Route as LayoutdoctorsDoctorPrescriptionsRouteImport } from './routes/_layout/(doctors)/doctor.prescriptions'
import { Route as LayoutdoctorsDoctorPatientsRouteImport } from './routes/_layout/(doctors)/doctor.patients'
import { Route as LayoutdoctorsDoctorDashboardRouteImport } from './routes/_layout/(doctors)/doctor.dashboard'
import { Route as LayoutdoctorsDoctorConsultationsRouteImport } from './routes/_layout/(doctors)/doctor.consultations'
import { Route as LayoutdoctorsDoctorAppointmentsRouteImport } from './routes/_layout/(doctors)/doctor.appointments'
import { Route as LayoutadminAdminUsersRouteImport } from './routes/_layout/(admin)/admin.users'
import { Route as LayoutadminAdminTransactionsRouteImport } from './routes/_layout/(admin)/admin.transactions'
import { Route as LayoutadminAdminSettingsRouteImport } from './routes/_layout/(admin)/admin.settings'
import { Route as LayoutadminAdminProfileRouteImport } from './routes/_layout/(admin)/admin.profile'
import { Route as LayoutadminAdminPrescriptionsRouteImport } from './routes/_layout/(admin)/admin.prescriptions'
import { Route as LayoutadminAdminPharmacyRouteImport } from './routes/_layout/(admin)/admin.pharmacy'
import { Route as LayoutadminAdminPharmacistRouteImport } from './routes/_layout/(admin)/admin.pharmacist'
import { Route as LayoutadminAdminPatientsRouteImport } from './routes/_layout/(admin)/admin.patients'
import { Route as LayoutadminAdminOrdersRouteImport } from './routes/_layout/(admin)/admin.orders'
import { Route as LayoutadminAdminMedicineRouteImport } from './routes/_layout/(admin)/admin.medicine'
import { Route as LayoutadminAdminInventoryRouteImport } from './routes/_layout/(admin)/admin.inventory'
import { Route as LayoutadminAdminDoctorsRouteImport } from './routes/_layout/(admin)/admin.doctors'
import { Route as LayoutadminAdminDashboardRouteImport } from './routes/_layout/(admin)/admin.dashboard'
import { Route as LayoutadminAdminConsultationsRouteImport } from './routes/_layout/(admin)/admin.consultations'
import { Route as LayoutadminAdminAppointmentsRouteImport } from './routes/_layout/(admin)/admin.appointments'
import { Route as LayoutadminAdminAdminsRouteImport } from './routes/_layout/(admin)/admin.admins'
import { Route as callCallJoinCallIdRouteImport } from './routes/(call)/call.join.$callId'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const callRouteRoute = callRouteRouteImport.update({
  id: '/(call)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/auth/forget-password',
  path: '/auth/forget-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutpharmacistPharmacistSettingsRoute =
  LayoutpharmacistPharmacistSettingsRouteImport.update({
    id: '/(pharmacist)/pharmacist/settings',
    path: '/pharmacist/settings',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpharmacistPharmacistPrescriptionsRoute =
  LayoutpharmacistPharmacistPrescriptionsRouteImport.update({
    id: '/(pharmacist)/pharmacist/prescriptions',
    path: '/pharmacist/prescriptions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpharmacistPharmacistOrdersRoute =
  LayoutpharmacistPharmacistOrdersRouteImport.update({
    id: '/(pharmacist)/pharmacist/orders',
    path: '/pharmacist/orders',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpharmacistPharmacistMedicineRoute =
  LayoutpharmacistPharmacistMedicineRouteImport.update({
    id: '/(pharmacist)/pharmacist/medicine',
    path: '/pharmacist/medicine',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpharmacistPharmacistInventoryRoute =
  LayoutpharmacistPharmacistInventoryRouteImport.update({
    id: '/(pharmacist)/pharmacist/inventory',
    path: '/pharmacist/inventory',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpharmacistPharmacistDashboardRoute =
  LayoutpharmacistPharmacistDashboardRouteImport.update({
    id: '/(pharmacist)/pharmacist/dashboard',
    path: '/pharmacist/dashboard',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpatientsPatientSettingsRoute =
  LayoutpatientsPatientSettingsRouteImport.update({
    id: '/(patients)/patient/settings',
    path: '/patient/settings',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpatientsPatientPrescriptionsRoute =
  LayoutpatientsPatientPrescriptionsRouteImport.update({
    id: '/(patients)/patient/prescriptions',
    path: '/patient/prescriptions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpatientsPatientDashboardRoute =
  LayoutpatientsPatientDashboardRouteImport.update({
    id: '/(patients)/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpatientsPatientConsultationsRoute =
  LayoutpatientsPatientConsultationsRouteImport.update({
    id: '/(patients)/patient/consultations',
    path: '/patient/consultations',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutpatientsPatientAppointmentsRoute =
  LayoutpatientsPatientAppointmentsRouteImport.update({
    id: '/(patients)/patient/appointments',
    path: '/patient/appointments',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorSettingsRoute =
  LayoutdoctorsDoctorSettingsRouteImport.update({
    id: '/(doctors)/doctor/settings',
    path: '/doctor/settings',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorPrescriptionsRoute =
  LayoutdoctorsDoctorPrescriptionsRouteImport.update({
    id: '/(doctors)/doctor/prescriptions',
    path: '/doctor/prescriptions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorPatientsRoute =
  LayoutdoctorsDoctorPatientsRouteImport.update({
    id: '/(doctors)/doctor/patients',
    path: '/doctor/patients',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorDashboardRoute =
  LayoutdoctorsDoctorDashboardRouteImport.update({
    id: '/(doctors)/doctor/dashboard',
    path: '/doctor/dashboard',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorConsultationsRoute =
  LayoutdoctorsDoctorConsultationsRouteImport.update({
    id: '/(doctors)/doctor/consultations',
    path: '/doctor/consultations',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutdoctorsDoctorAppointmentsRoute =
  LayoutdoctorsDoctorAppointmentsRouteImport.update({
    id: '/(doctors)/doctor/appointments',
    path: '/doctor/appointments',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminUsersRoute = LayoutadminAdminUsersRouteImport.update({
  id: '/(admin)/admin/users',
  path: '/admin/users',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminTransactionsRoute =
  LayoutadminAdminTransactionsRouteImport.update({
    id: '/(admin)/admin/transactions',
    path: '/admin/transactions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminSettingsRoute =
  LayoutadminAdminSettingsRouteImport.update({
    id: '/(admin)/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminProfileRoute = LayoutadminAdminProfileRouteImport.update({
  id: '/(admin)/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminPrescriptionsRoute =
  LayoutadminAdminPrescriptionsRouteImport.update({
    id: '/(admin)/admin/prescriptions',
    path: '/admin/prescriptions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminPharmacyRoute =
  LayoutadminAdminPharmacyRouteImport.update({
    id: '/(admin)/admin/pharmacy',
    path: '/admin/pharmacy',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminPharmacistRoute =
  LayoutadminAdminPharmacistRouteImport.update({
    id: '/(admin)/admin/pharmacist',
    path: '/admin/pharmacist',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminPatientsRoute =
  LayoutadminAdminPatientsRouteImport.update({
    id: '/(admin)/admin/patients',
    path: '/admin/patients',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminOrdersRoute = LayoutadminAdminOrdersRouteImport.update({
  id: '/(admin)/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminMedicineRoute =
  LayoutadminAdminMedicineRouteImport.update({
    id: '/(admin)/admin/medicine',
    path: '/admin/medicine',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminInventoryRoute =
  LayoutadminAdminInventoryRouteImport.update({
    id: '/(admin)/admin/inventory',
    path: '/admin/inventory',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminDoctorsRoute = LayoutadminAdminDoctorsRouteImport.update({
  id: '/(admin)/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutadminAdminDashboardRoute =
  LayoutadminAdminDashboardRouteImport.update({
    id: '/(admin)/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminConsultationsRoute =
  LayoutadminAdminConsultationsRouteImport.update({
    id: '/(admin)/admin/consultations',
    path: '/admin/consultations',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminAppointmentsRoute =
  LayoutadminAdminAppointmentsRouteImport.update({
    id: '/(admin)/admin/appointments',
    path: '/admin/appointments',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutadminAdminAdminsRoute = LayoutadminAdminAdminsRouteImport.update({
  id: '/(admin)/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const callCallJoinCallIdRoute = callCallJoinCallIdRouteImport.update({
  id: '/call/join/$callId',
  path: '/call/join/$callId',
  getParentRoute: () => callRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof callRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/call/join/$callId': typeof callCallJoinCallIdRoute
  '/admin/admins': typeof LayoutadminAdminAdminsRoute
  '/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/admin/orders': typeof LayoutadminAdminOrdersRoute
  '/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/admin/pharmacist': typeof LayoutadminAdminPharmacistRoute
  '/admin/pharmacy': typeof LayoutadminAdminPharmacyRoute
  '/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/admin/profile': typeof LayoutadminAdminProfileRoute
  '/admin/settings': typeof LayoutadminAdminSettingsRoute
  '/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/admin/users': typeof LayoutadminAdminUsersRoute
  '/doctor/appointments': typeof LayoutdoctorsDoctorAppointmentsRoute
  '/doctor/consultations': typeof LayoutdoctorsDoctorConsultationsRoute
  '/doctor/dashboard': typeof LayoutdoctorsDoctorDashboardRoute
  '/doctor/patients': typeof LayoutdoctorsDoctorPatientsRoute
  '/doctor/prescriptions': typeof LayoutdoctorsDoctorPrescriptionsRoute
  '/doctor/settings': typeof LayoutdoctorsDoctorSettingsRoute
  '/patient/appointments': typeof LayoutpatientsPatientAppointmentsRoute
  '/patient/consultations': typeof LayoutpatientsPatientConsultationsRoute
  '/patient/dashboard': typeof LayoutpatientsPatientDashboardRoute
  '/patient/prescriptions': typeof LayoutpatientsPatientPrescriptionsRoute
  '/patient/settings': typeof LayoutpatientsPatientSettingsRoute
  '/pharmacist/dashboard': typeof LayoutpharmacistPharmacistDashboardRoute
  '/pharmacist/inventory': typeof LayoutpharmacistPharmacistInventoryRoute
  '/pharmacist/medicine': typeof LayoutpharmacistPharmacistMedicineRoute
  '/pharmacist/orders': typeof LayoutpharmacistPharmacistOrdersRoute
  '/pharmacist/prescriptions': typeof LayoutpharmacistPharmacistPrescriptionsRoute
  '/pharmacist/settings': typeof LayoutpharmacistPharmacistSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof callRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/call/join/$callId': typeof callCallJoinCallIdRoute
  '/admin/admins': typeof LayoutadminAdminAdminsRoute
  '/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/admin/orders': typeof LayoutadminAdminOrdersRoute
  '/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/admin/pharmacist': typeof LayoutadminAdminPharmacistRoute
  '/admin/pharmacy': typeof LayoutadminAdminPharmacyRoute
  '/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/admin/profile': typeof LayoutadminAdminProfileRoute
  '/admin/settings': typeof LayoutadminAdminSettingsRoute
  '/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/admin/users': typeof LayoutadminAdminUsersRoute
  '/doctor/appointments': typeof LayoutdoctorsDoctorAppointmentsRoute
  '/doctor/consultations': typeof LayoutdoctorsDoctorConsultationsRoute
  '/doctor/dashboard': typeof LayoutdoctorsDoctorDashboardRoute
  '/doctor/patients': typeof LayoutdoctorsDoctorPatientsRoute
  '/doctor/prescriptions': typeof LayoutdoctorsDoctorPrescriptionsRoute
  '/doctor/settings': typeof LayoutdoctorsDoctorSettingsRoute
  '/patient/appointments': typeof LayoutpatientsPatientAppointmentsRoute
  '/patient/consultations': typeof LayoutpatientsPatientConsultationsRoute
  '/patient/dashboard': typeof LayoutpatientsPatientDashboardRoute
  '/patient/prescriptions': typeof LayoutpatientsPatientPrescriptionsRoute
  '/patient/settings': typeof LayoutpatientsPatientSettingsRoute
  '/pharmacist/dashboard': typeof LayoutpharmacistPharmacistDashboardRoute
  '/pharmacist/inventory': typeof LayoutpharmacistPharmacistInventoryRoute
  '/pharmacist/medicine': typeof LayoutpharmacistPharmacistMedicineRoute
  '/pharmacist/orders': typeof LayoutpharmacistPharmacistOrdersRoute
  '/pharmacist/prescriptions': typeof LayoutpharmacistPharmacistPrescriptionsRoute
  '/pharmacist/settings': typeof LayoutpharmacistPharmacistSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(call)': typeof callRouteRouteWithChildren
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forget-password': typeof AuthForgetPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(call)/call/join/$callId': typeof callCallJoinCallIdRoute
  '/_layout/(admin)/admin/admins': typeof LayoutadminAdminAdminsRoute
  '/_layout/(admin)/admin/appointments': typeof LayoutadminAdminAppointmentsRoute
  '/_layout/(admin)/admin/consultations': typeof LayoutadminAdminConsultationsRoute
  '/_layout/(admin)/admin/dashboard': typeof LayoutadminAdminDashboardRoute
  '/_layout/(admin)/admin/doctors': typeof LayoutadminAdminDoctorsRoute
  '/_layout/(admin)/admin/inventory': typeof LayoutadminAdminInventoryRoute
  '/_layout/(admin)/admin/medicine': typeof LayoutadminAdminMedicineRoute
  '/_layout/(admin)/admin/orders': typeof LayoutadminAdminOrdersRoute
  '/_layout/(admin)/admin/patients': typeof LayoutadminAdminPatientsRoute
  '/_layout/(admin)/admin/pharmacist': typeof LayoutadminAdminPharmacistRoute
  '/_layout/(admin)/admin/pharmacy': typeof LayoutadminAdminPharmacyRoute
  '/_layout/(admin)/admin/prescriptions': typeof LayoutadminAdminPrescriptionsRoute
  '/_layout/(admin)/admin/profile': typeof LayoutadminAdminProfileRoute
  '/_layout/(admin)/admin/settings': typeof LayoutadminAdminSettingsRoute
  '/_layout/(admin)/admin/transactions': typeof LayoutadminAdminTransactionsRoute
  '/_layout/(admin)/admin/users': typeof LayoutadminAdminUsersRoute
  '/_layout/(doctors)/doctor/appointments': typeof LayoutdoctorsDoctorAppointmentsRoute
  '/_layout/(doctors)/doctor/consultations': typeof LayoutdoctorsDoctorConsultationsRoute
  '/_layout/(doctors)/doctor/dashboard': typeof LayoutdoctorsDoctorDashboardRoute
  '/_layout/(doctors)/doctor/patients': typeof LayoutdoctorsDoctorPatientsRoute
  '/_layout/(doctors)/doctor/prescriptions': typeof LayoutdoctorsDoctorPrescriptionsRoute
  '/_layout/(doctors)/doctor/settings': typeof LayoutdoctorsDoctorSettingsRoute
  '/_layout/(patients)/patient/appointments': typeof LayoutpatientsPatientAppointmentsRoute
  '/_layout/(patients)/patient/consultations': typeof LayoutpatientsPatientConsultationsRoute
  '/_layout/(patients)/patient/dashboard': typeof LayoutpatientsPatientDashboardRoute
  '/_layout/(patients)/patient/prescriptions': typeof LayoutpatientsPatientPrescriptionsRoute
  '/_layout/(patients)/patient/settings': typeof LayoutpatientsPatientSettingsRoute
  '/_layout/(pharmacist)/pharmacist/dashboard': typeof LayoutpharmacistPharmacistDashboardRoute
  '/_layout/(pharmacist)/pharmacist/inventory': typeof LayoutpharmacistPharmacistInventoryRoute
  '/_layout/(pharmacist)/pharmacist/medicine': typeof LayoutpharmacistPharmacistMedicineRoute
  '/_layout/(pharmacist)/pharmacist/orders': typeof LayoutpharmacistPharmacistOrdersRoute
  '/_layout/(pharmacist)/pharmacist/prescriptions': typeof LayoutpharmacistPharmacistPrescriptionsRoute
  '/_layout/(pharmacist)/pharmacist/settings': typeof LayoutpharmacistPharmacistSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/call/join/$callId'
    | '/admin/admins'
    | '/admin/appointments'
    | '/admin/consultations'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/inventory'
    | '/admin/medicine'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/pharmacist'
    | '/admin/pharmacy'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/consultations'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/consultations'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/settings'
    | '/pharmacist/dashboard'
    | '/pharmacist/inventory'
    | '/pharmacist/medicine'
    | '/pharmacist/orders'
    | '/pharmacist/prescriptions'
    | '/pharmacist/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/call/join/$callId'
    | '/admin/admins'
    | '/admin/appointments'
    | '/admin/consultations'
    | '/admin/dashboard'
    | '/admin/doctors'
    | '/admin/inventory'
    | '/admin/medicine'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/pharmacist'
    | '/admin/pharmacy'
    | '/admin/prescriptions'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/users'
    | '/doctor/appointments'
    | '/doctor/consultations'
    | '/doctor/dashboard'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/settings'
    | '/patient/appointments'
    | '/patient/consultations'
    | '/patient/dashboard'
    | '/patient/prescriptions'
    | '/patient/settings'
    | '/pharmacist/dashboard'
    | '/pharmacist/inventory'
    | '/pharmacist/medicine'
    | '/pharmacist/orders'
    | '/pharmacist/prescriptions'
    | '/pharmacist/settings'
  id:
    | '__root__'
    | '/'
    | '/(call)'
    | '/_layout'
    | '/auth/callback'
    | '/auth/forget-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/(call)/call/join/$callId'
    | '/_layout/(admin)/admin/admins'
    | '/_layout/(admin)/admin/appointments'
    | '/_layout/(admin)/admin/consultations'
    | '/_layout/(admin)/admin/dashboard'
    | '/_layout/(admin)/admin/doctors'
    | '/_layout/(admin)/admin/inventory'
    | '/_layout/(admin)/admin/medicine'
    | '/_layout/(admin)/admin/orders'
    | '/_layout/(admin)/admin/patients'
    | '/_layout/(admin)/admin/pharmacist'
    | '/_layout/(admin)/admin/pharmacy'
    | '/_layout/(admin)/admin/prescriptions'
    | '/_layout/(admin)/admin/profile'
    | '/_layout/(admin)/admin/settings'
    | '/_layout/(admin)/admin/transactions'
    | '/_layout/(admin)/admin/users'
    | '/_layout/(doctors)/doctor/appointments'
    | '/_layout/(doctors)/doctor/consultations'
    | '/_layout/(doctors)/doctor/dashboard'
    | '/_layout/(doctors)/doctor/patients'
    | '/_layout/(doctors)/doctor/prescriptions'
    | '/_layout/(doctors)/doctor/settings'
    | '/_layout/(patients)/patient/appointments'
    | '/_layout/(patients)/patient/consultations'
    | '/_layout/(patients)/patient/dashboard'
    | '/_layout/(patients)/patient/prescriptions'
    | '/_layout/(patients)/patient/settings'
    | '/_layout/(pharmacist)/pharmacist/dashboard'
    | '/_layout/(pharmacist)/pharmacist/inventory'
    | '/_layout/(pharmacist)/pharmacist/medicine'
    | '/_layout/(pharmacist)/pharmacist/orders'
    | '/_layout/(pharmacist)/pharmacist/prescriptions'
    | '/_layout/(pharmacist)/pharmacist/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  callRouteRoute: typeof callRouteRouteWithChildren
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(call)': {
      id: '/(call)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof callRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forget-password': {
      id: '/auth/forget-password'
      path: '/auth/forget-password'
      fullPath: '/auth/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/(pharmacist)/pharmacist/settings': {
      id: '/_layout/(pharmacist)/pharmacist/settings'
      path: '/pharmacist/settings'
      fullPath: '/pharmacist/settings'
      preLoaderRoute: typeof LayoutpharmacistPharmacistSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(pharmacist)/pharmacist/prescriptions': {
      id: '/_layout/(pharmacist)/pharmacist/prescriptions'
      path: '/pharmacist/prescriptions'
      fullPath: '/pharmacist/prescriptions'
      preLoaderRoute: typeof LayoutpharmacistPharmacistPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(pharmacist)/pharmacist/orders': {
      id: '/_layout/(pharmacist)/pharmacist/orders'
      path: '/pharmacist/orders'
      fullPath: '/pharmacist/orders'
      preLoaderRoute: typeof LayoutpharmacistPharmacistOrdersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(pharmacist)/pharmacist/medicine': {
      id: '/_layout/(pharmacist)/pharmacist/medicine'
      path: '/pharmacist/medicine'
      fullPath: '/pharmacist/medicine'
      preLoaderRoute: typeof LayoutpharmacistPharmacistMedicineRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(pharmacist)/pharmacist/inventory': {
      id: '/_layout/(pharmacist)/pharmacist/inventory'
      path: '/pharmacist/inventory'
      fullPath: '/pharmacist/inventory'
      preLoaderRoute: typeof LayoutpharmacistPharmacistInventoryRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(pharmacist)/pharmacist/dashboard': {
      id: '/_layout/(pharmacist)/pharmacist/dashboard'
      path: '/pharmacist/dashboard'
      fullPath: '/pharmacist/dashboard'
      preLoaderRoute: typeof LayoutpharmacistPharmacistDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(patients)/patient/settings': {
      id: '/_layout/(patients)/patient/settings'
      path: '/patient/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof LayoutpatientsPatientSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(patients)/patient/prescriptions': {
      id: '/_layout/(patients)/patient/prescriptions'
      path: '/patient/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof LayoutpatientsPatientPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(patients)/patient/dashboard': {
      id: '/_layout/(patients)/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof LayoutpatientsPatientDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(patients)/patient/consultations': {
      id: '/_layout/(patients)/patient/consultations'
      path: '/patient/consultations'
      fullPath: '/patient/consultations'
      preLoaderRoute: typeof LayoutpatientsPatientConsultationsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(patients)/patient/appointments': {
      id: '/_layout/(patients)/patient/appointments'
      path: '/patient/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof LayoutpatientsPatientAppointmentsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/settings': {
      id: '/_layout/(doctors)/doctor/settings'
      path: '/doctor/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof LayoutdoctorsDoctorSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/prescriptions': {
      id: '/_layout/(doctors)/doctor/prescriptions'
      path: '/doctor/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof LayoutdoctorsDoctorPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/patients': {
      id: '/_layout/(doctors)/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof LayoutdoctorsDoctorPatientsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/dashboard': {
      id: '/_layout/(doctors)/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof LayoutdoctorsDoctorDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/consultations': {
      id: '/_layout/(doctors)/doctor/consultations'
      path: '/doctor/consultations'
      fullPath: '/doctor/consultations'
      preLoaderRoute: typeof LayoutdoctorsDoctorConsultationsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(doctors)/doctor/appointments': {
      id: '/_layout/(doctors)/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof LayoutdoctorsDoctorAppointmentsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/users': {
      id: '/_layout/(admin)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutadminAdminUsersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/transactions': {
      id: '/_layout/(admin)/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof LayoutadminAdminTransactionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/settings': {
      id: '/_layout/(admin)/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof LayoutadminAdminSettingsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/profile': {
      id: '/_layout/(admin)/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof LayoutadminAdminProfileRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/prescriptions': {
      id: '/_layout/(admin)/admin/prescriptions'
      path: '/admin/prescriptions'
      fullPath: '/admin/prescriptions'
      preLoaderRoute: typeof LayoutadminAdminPrescriptionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/pharmacy': {
      id: '/_layout/(admin)/admin/pharmacy'
      path: '/admin/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof LayoutadminAdminPharmacyRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/pharmacist': {
      id: '/_layout/(admin)/admin/pharmacist'
      path: '/admin/pharmacist'
      fullPath: '/admin/pharmacist'
      preLoaderRoute: typeof LayoutadminAdminPharmacistRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/patients': {
      id: '/_layout/(admin)/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof LayoutadminAdminPatientsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/orders': {
      id: '/_layout/(admin)/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof LayoutadminAdminOrdersRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/medicine': {
      id: '/_layout/(admin)/admin/medicine'
      path: '/admin/medicine'
      fullPath: '/admin/medicine'
      preLoaderRoute: typeof LayoutadminAdminMedicineRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/inventory': {
      id: '/_layout/(admin)/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof LayoutadminAdminInventoryRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/doctors': {
      id: '/_layout/(admin)/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof LayoutadminAdminDoctorsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/dashboard': {
      id: '/_layout/(admin)/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof LayoutadminAdminDashboardRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/consultations': {
      id: '/_layout/(admin)/admin/consultations'
      path: '/admin/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof LayoutadminAdminConsultationsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/appointments': {
      id: '/_layout/(admin)/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof LayoutadminAdminAppointmentsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/(admin)/admin/admins': {
      id: '/_layout/(admin)/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof LayoutadminAdminAdminsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/(call)/call/join/$callId': {
      id: '/(call)/call/join/$callId'
      path: '/call/join/$callId'
      fullPath: '/call/join/$callId'
      preLoaderRoute: typeof callCallJoinCallIdRouteImport
      parentRoute: typeof callRouteRoute
    }
  }
}

interface callRouteRouteChildren {
  callCallJoinCallIdRoute: typeof callCallJoinCallIdRoute
}

const callRouteRouteChildren: callRouteRouteChildren = {
  callCallJoinCallIdRoute: callCallJoinCallIdRoute,
}

const callRouteRouteWithChildren = callRouteRoute._addFileChildren(
  callRouteRouteChildren,
)

interface LayoutRouteRouteChildren {
  LayoutadminAdminAdminsRoute: typeof LayoutadminAdminAdminsRoute
  LayoutadminAdminAppointmentsRoute: typeof LayoutadminAdminAppointmentsRoute
  LayoutadminAdminConsultationsRoute: typeof LayoutadminAdminConsultationsRoute
  LayoutadminAdminDashboardRoute: typeof LayoutadminAdminDashboardRoute
  LayoutadminAdminDoctorsRoute: typeof LayoutadminAdminDoctorsRoute
  LayoutadminAdminInventoryRoute: typeof LayoutadminAdminInventoryRoute
  LayoutadminAdminMedicineRoute: typeof LayoutadminAdminMedicineRoute
  LayoutadminAdminOrdersRoute: typeof LayoutadminAdminOrdersRoute
  LayoutadminAdminPatientsRoute: typeof LayoutadminAdminPatientsRoute
  LayoutadminAdminPharmacistRoute: typeof LayoutadminAdminPharmacistRoute
  LayoutadminAdminPharmacyRoute: typeof LayoutadminAdminPharmacyRoute
  LayoutadminAdminPrescriptionsRoute: typeof LayoutadminAdminPrescriptionsRoute
  LayoutadminAdminProfileRoute: typeof LayoutadminAdminProfileRoute
  LayoutadminAdminSettingsRoute: typeof LayoutadminAdminSettingsRoute
  LayoutadminAdminTransactionsRoute: typeof LayoutadminAdminTransactionsRoute
  LayoutadminAdminUsersRoute: typeof LayoutadminAdminUsersRoute
  LayoutdoctorsDoctorAppointmentsRoute: typeof LayoutdoctorsDoctorAppointmentsRoute
  LayoutdoctorsDoctorConsultationsRoute: typeof LayoutdoctorsDoctorConsultationsRoute
  LayoutdoctorsDoctorDashboardRoute: typeof LayoutdoctorsDoctorDashboardRoute
  LayoutdoctorsDoctorPatientsRoute: typeof LayoutdoctorsDoctorPatientsRoute
  LayoutdoctorsDoctorPrescriptionsRoute: typeof LayoutdoctorsDoctorPrescriptionsRoute
  LayoutdoctorsDoctorSettingsRoute: typeof LayoutdoctorsDoctorSettingsRoute
  LayoutpatientsPatientAppointmentsRoute: typeof LayoutpatientsPatientAppointmentsRoute
  LayoutpatientsPatientConsultationsRoute: typeof LayoutpatientsPatientConsultationsRoute
  LayoutpatientsPatientDashboardRoute: typeof LayoutpatientsPatientDashboardRoute
  LayoutpatientsPatientPrescriptionsRoute: typeof LayoutpatientsPatientPrescriptionsRoute
  LayoutpatientsPatientSettingsRoute: typeof LayoutpatientsPatientSettingsRoute
  LayoutpharmacistPharmacistDashboardRoute: typeof LayoutpharmacistPharmacistDashboardRoute
  LayoutpharmacistPharmacistInventoryRoute: typeof LayoutpharmacistPharmacistInventoryRoute
  LayoutpharmacistPharmacistMedicineRoute: typeof LayoutpharmacistPharmacistMedicineRoute
  LayoutpharmacistPharmacistOrdersRoute: typeof LayoutpharmacistPharmacistOrdersRoute
  LayoutpharmacistPharmacistPrescriptionsRoute: typeof LayoutpharmacistPharmacistPrescriptionsRoute
  LayoutpharmacistPharmacistSettingsRoute: typeof LayoutpharmacistPharmacistSettingsRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutadminAdminAdminsRoute: LayoutadminAdminAdminsRoute,
  LayoutadminAdminAppointmentsRoute: LayoutadminAdminAppointmentsRoute,
  LayoutadminAdminConsultationsRoute: LayoutadminAdminConsultationsRoute,
  LayoutadminAdminDashboardRoute: LayoutadminAdminDashboardRoute,
  LayoutadminAdminDoctorsRoute: LayoutadminAdminDoctorsRoute,
  LayoutadminAdminInventoryRoute: LayoutadminAdminInventoryRoute,
  LayoutadminAdminMedicineRoute: LayoutadminAdminMedicineRoute,
  LayoutadminAdminOrdersRoute: LayoutadminAdminOrdersRoute,
  LayoutadminAdminPatientsRoute: LayoutadminAdminPatientsRoute,
  LayoutadminAdminPharmacistRoute: LayoutadminAdminPharmacistRoute,
  LayoutadminAdminPharmacyRoute: LayoutadminAdminPharmacyRoute,
  LayoutadminAdminPrescriptionsRoute: LayoutadminAdminPrescriptionsRoute,
  LayoutadminAdminProfileRoute: LayoutadminAdminProfileRoute,
  LayoutadminAdminSettingsRoute: LayoutadminAdminSettingsRoute,
  LayoutadminAdminTransactionsRoute: LayoutadminAdminTransactionsRoute,
  LayoutadminAdminUsersRoute: LayoutadminAdminUsersRoute,
  LayoutdoctorsDoctorAppointmentsRoute: LayoutdoctorsDoctorAppointmentsRoute,
  LayoutdoctorsDoctorConsultationsRoute: LayoutdoctorsDoctorConsultationsRoute,
  LayoutdoctorsDoctorDashboardRoute: LayoutdoctorsDoctorDashboardRoute,
  LayoutdoctorsDoctorPatientsRoute: LayoutdoctorsDoctorPatientsRoute,
  LayoutdoctorsDoctorPrescriptionsRoute: LayoutdoctorsDoctorPrescriptionsRoute,
  LayoutdoctorsDoctorSettingsRoute: LayoutdoctorsDoctorSettingsRoute,
  LayoutpatientsPatientAppointmentsRoute:
    LayoutpatientsPatientAppointmentsRoute,
  LayoutpatientsPatientConsultationsRoute:
    LayoutpatientsPatientConsultationsRoute,
  LayoutpatientsPatientDashboardRoute: LayoutpatientsPatientDashboardRoute,
  LayoutpatientsPatientPrescriptionsRoute:
    LayoutpatientsPatientPrescriptionsRoute,
  LayoutpatientsPatientSettingsRoute: LayoutpatientsPatientSettingsRoute,
  LayoutpharmacistPharmacistDashboardRoute:
    LayoutpharmacistPharmacistDashboardRoute,
  LayoutpharmacistPharmacistInventoryRoute:
    LayoutpharmacistPharmacistInventoryRoute,
  LayoutpharmacistPharmacistMedicineRoute:
    LayoutpharmacistPharmacistMedicineRoute,
  LayoutpharmacistPharmacistOrdersRoute: LayoutpharmacistPharmacistOrdersRoute,
  LayoutpharmacistPharmacistPrescriptionsRoute:
    LayoutpharmacistPharmacistPrescriptionsRoute,
  LayoutpharmacistPharmacistSettingsRoute:
    LayoutpharmacistPharmacistSettingsRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  callRouteRoute: callRouteRouteWithChildren,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
